export default {
    "RUS": {"name": "Russia", "eloCode": "RU", "isoCode": "RU", "group": "A"},
    "KSA": {"name": "Saudi Arabia", "eloCode": "SA", "isoCode": "SA", "group": "A"},
    "EGY": {"name": "Egypt", "eloCode": "EG", "isoCode": "EG", "group": "A"},
    "URU": {"name": "Uruguay", "eloCode": "UY", "isoCode": "UY", "group": "A"},
    "POR": {"name": "Portugal", "eloCode": "PT", "isoCode": "PT", "group": "B"},
    "ESP": {"name": "Spain", "eloCode": "ES", "isoCode": "ES", "group": "B"},
    "MAR": {"name": "Morocco", "eloCode": "MA", "isoCode": "MA", "group": "B"},
    "IRN": {"name": "Iran", "eloCode": "IR", "isoCode": "IR", "group": "B"},
    "FRA": {"name": "France", "eloCode": "FR", "isoCode": "FR", "group": "C"},
    "AUS": {"name": "Australia", "eloCode": "AU", "isoCode": "AU", "group": "C"},
    "PER": {"name": "Peru", "eloCode": "PE", "isoCode": "PE", "group": "C"},
    "DEN": {"name": "Denmark", "eloCode": "DK", "isoCode": "DK", "group": "C"},
    "ARG": {"name": "Argentina", "eloCode": "AR", "isoCode": "AR", "group": "D"},
    "ISL": {"name": "Iceland", "eloCode": "IS", "isoCode": "IS", "group": "D"},
    "CRO": {"name": "Croatia", "eloCode": "HR", "isoCode": "HR", "group": "D"},
    "NGA": {"name": "Nigeria", "eloCode": "NG", "isoCode": "NG", "group": "D"},
    "BRA": {"name": "Brazil", "eloCode": "BR", "isoCode": "BR", "group": "E"},
    "SUI": {"name": "Switzerland", "eloCode": "CH", "isoCode": "CH", "group": "E"},
    "CRC": {"name": "Costa Rica", "eloCode": "CR", "isoCode": "CR", "group": "E"},
    "SRB": {"name": "Serbia", "eloCode": "RS", "isoCode": "RS", "group": "E"},
    "GER": {"name": "Germany", "eloCode": "DE", "isoCode": "DE", "group": "F"},
    "MEX": {"name": "Mexico", "eloCode": "MX", "isoCode": "MX", "group": "F"},
    "SWE": {"name": "Sweden", "eloCode": "SE", "isoCode": "SE", "group": "F"},
    "KOR": {"name": "Korea Republic", "eloCode": "KR", "isoCode": "KR", "group": "F"},
    "BEL": {"name": "Belgium", "eloCode": "BE", "isoCode": "BE", "group": "G"},
    "PAN": {"name": "Panama", "eloCode": "PA", "isoCode": "PA", "group": "G"},
    "TUN": {"name": "Tunisia", "eloCode": "TN", "isoCode": "TN", "group": "G"},
    "ENG": {"name": "England", "eloCode": "EN", "isoCode": "GB", "group": "G"},
    "POL": {"name": "Poland", "eloCode": "PL", "isoCode": "PL", "group": "H"},
    "SEN": {"name": "Senegal", "eloCode": "SN", "isoCode": "SN", "group": "H"},
    "COL": {"name": "Colombia", "eloCode": "CO", "isoCode": "CO", "group": "H"},
    "JPN": {"name": "Japan", "eloCode": "JP", "isoCode": "JP", "group": "H"}
}