export default {
    "FRA": {"name": "France", "eloCode": "FR", "isoCode": "FR", "group": "A"},
    "KOR": {"name": "Korea Republic", "eloCode": "KR", "isoCode": "KR", "group": "A"},
    "NOR": {"name": "Norway", "eloCode": "NO", "isoCode": "NO", "group": "A"},
    "NGA": {"name": "Nigeria", "eloCode": "NG", "isoCode": "NG", "group": "A"},
    "GER": {"name": "Germany", "eloCode": "DE", "isoCode": "DE", "group": "B"},
    "CHN": {"name": "China", "eloCode": "CN", "isoCode": "CN", "group": "B"},
    "ESP": {"name": "Spain", "eloCode": "ES", "isoCode": "ES", "group": "B"},
    "RSA": {"name": "South Africa", "eloCode": "ZA", "isoCode": "ZA", "group": "B"},
    "AUS": {"name": "Australia", "eloCode": "AU", "isoCode": "AU", "group": "C"},
    "ITA": {"name": "Italy", "eloCode": "IT", "isoCode": "IT", "group": "C"},
    "BRA": {"name": "Brazil", "eloCode": "BR", "isoCode": "BR", "group": "C"},
    "JAM": {"name": "Jamaica", "eloCode": "JM", "isoCode": "JM", "group": "C"},
    "ENG": {"name": "England", "eloCode": "EN", "isoCode": "GB-ENG", "group": "D"},
    "SCO": {"name": "Scotland", "eloCode": "SQ", "isoCode": "GB-SCT", "group": "D"},
    "ARG": {"name": "Argentina", "eloCode": "AR", "isoCode": "AR", "group": "D"},
    "JPN": {"name": "Japan", "eloCode": "JP", "isoCode": "JP", "group": "D"},
    "CAN": {"name": "Canada", "eloCode": "CA", "isoCode": "CA", "group": "E"},
    "CMR": {"name": "Cameroon", "eloCode": "CM", "isoCode": "CM", "group": "E"},
    "NZL": {"name": "New Zealand", "eloCode": "NZ", "isoCode": "NZ", "group": "E"},
    "NED": {"name": "Netherlands", "eloCode": "NL", "isoCode": "NL", "group": "E"},
    "USA": {"name": "USA", "eloCode": "US", "isoCode": "US", "group": "F"},
    "THA": {"name": "Thailand", "eloCode": "TH", "isoCode": "TH", "group": "F"},
    "CHI": {"name": "Chile", "eloCode": "CL", "isoCode": "CL", "group": "F"},
    "SWE": {"name": "Sweden", "eloCode": "SE", "isoCode": "SE", "group": "F"}
}